version: '3.8'
services:
  stats-service:
    build: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER_PORT=9090

  main-service:
    build: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - FEIGN_URL=http://stats-server:9090
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password